

pipeline{
	agent any

	stages {

		stage('Checkout') {
			steps {
			// 소스코드 체크아웃 
			checkout scm
			} 
		}

		stage('Pre-Build') { 
			steps {
				script{
					// make Book class into classes folder (in workspace)
					sh 'mkdir -p classes'
					sh 'javac -encoding UTF-8 -d classes /Users/nimo/Desktop/jenkinsPractice/Practice/src/app/Book.java'

					echo "Pre-Build finished!!! :D"
				}

			}
			
		}
		

		stage('Build') { 
			steps {
				script{

				// mac code here
				// JUnit 5 테스트 실행을 위한 classpath 설정
				def classpath = "java -jar /Users/nimo/Desktop/jenkinsPractice/Practice/.settings/junit-platform-console-standalone-1.7.1.jar"
				sh 'java -cp classes:/Users/nimo/Desktop/jenkinsPractice/Practice/.settings/junit-platform-console-standalone-1.7.1.jar org.junit.platform.console.ConsoleLauncher --scan-class-path'
				sh 'pwd'
				
				} 
				dir ("Practice/src/app") {
					sh 'javac PerformanceTest.java'
				}

				echo "Build finished!!! :D"

			}
		}

		stage('Test') { 
			steps {
				// script{

				// // mac code here
				// // JUnit 5 테스트 실행을 위한 classpath 설정
				// def classpath = "java -jar /Users/nimo/Desktop/jenkinsPractice/Practice/.settings/junit-platform-console-standalone-1.7.1.jar"
				// sh 'java -cp classes:/Users/nimo/Desktop/jenkinsPractice/Practice/.settings/junit-platform-console-standalone-1.7.1.jar org.junit.platform.console.ConsoleLauncher --scan-class-path'
				// sh 'pwd'
				
				// } 
				dir ("Practice/src/app") {
					sh 'java PerformanceTest > junit_test_results.txt'
				}

				echo "Test finished!!! :D"

			}
		}

	}

	post {
		always{
			dir ("Practice/src/app") {
				archiveArtifacts 'junit_test_results.txt'
			}

		}
		
	}

}


