// pipeline { 
// 	agent any
// 	stages {
// 		stage('Checkout') {
// 			steps {
// 				echo "git check out"
// 			// 소스코드 체크아웃 checkout scm
// 			} 
// 		}
// 		stage('Build') { 
// 			steps {
// 			echo "build build"
// 			// Java 파일들을 컴파일하여 생성된 클래스 파일을 Practice/src 디렉토리에 저장 // window 일 경우 bat
// 			sh 'javac -encoding UTF-8 -d Practice/src Practice/src/java_5_21/Book.java'
// 			}
// 		}
// 		// stage('Test') { 
// 		// 	steps {
// 		// 		echo "testing..."
// 		// 	// JUnit 5 테스트 실행을 위한 classpath 설정
// 		// 	def classpath = "Practice/src;lib/; path/to/eclipse/plugins/junit-platform-console-standalone- 1.7.1.jar"
// 		// 	// JUnit 5 테스트 실행
// 		// 	bat 'java -cp Practice/src;lib/; path/to/eclipse/plugins/junit-
// 		// 	platform-console-standalone-1.7.1.jar org.junit.platform.console.ConsoleLauncher --scan-classpath > test_results.txt'
// 		// 	} 
// 		}
// 	} post {
// 		always {
// 		// 테스트 결과 파일을 저장하기 위해 아카이브 archiveArtifacts 'test_results.txt'
// 		} failure {
// 		echo "build failed" }
// 		success {
// 		echo "build success"

// 		} 
// 	}
// }

pipeline{
	agent any
	stages {
		stage('Checkout') {
			steps {
			// 소스코드 체크아웃 
			checkout scm
			} 
		}

		stage('Build') { 
			steps {
				script{
				 sh 'mkdir -p classes'
				 sh 'javac -encoding UTF-8 -d classes /Users/nimo/Desktop/jenkinsPractice/Practice/src/app/Book.java'
				}
			echo "Build finished!!! :D"
			// Java 파일들을 컴파일하여 생성된 클래스 파일을 classes 디렉토리에 저장 // window 일 경우 bat
			// sh 'javac -encoding UTF-8 -d classes /Users/nimo/Desktop/jenkinsPractice/Practice/src/app/Book.java'
			}
		}


		stage('Test1') { 
			steps {
				script{
				// JUnit 5 테스트 실행을 위한 classpath 설정

				def classpath = "java -jar /Users/nimo/Desktop/jenkinsPractice/Practice/.settings/junit-platform-console-standalone-1.7.1.jar"
			
				
				// def classpath = "classes; User/nimo/Downloads/junit-platform-console-standalone-1.7.1.jar"
				// // JUnit 5 테스트 실행
				// bat 'java -cp classes; User/nimo/Downloads/junit-platform-console-standalone-1.7.1.jar org.junit.platform.console.ConsoleLauncher --scan-classpath > test_results.txt'
				// }
				// JUnit 5 테스트 실행을 위한 classpath 설정
				// def classpath = "path/to/eclipse/plugins/junit-platform-console-standalone- 1.7.1.jar"
				// // JUnit 5 테스트 실행
				// bat 'java -cp Practice/src/output;lib/; path/to/eclipse/plugins/junit-
				// platform-console-standalone-1.7.1.jar org.junit.platform.console.ConsoleLauncher --scan-classpath > test_results.txt'
				} 
			}
		}

		stage('Test2') { 
			steps {
				script{
					// JUnit 5 테스트 실행
				sh 'java -cp classes:/Users/nimo/Desktop/jenkinsPractice/Practice/.settings/junit-platform-console-standalone-1.7.1.jar org.junit.platform.console.ConsoleLauncher --scan-class-path > test_results.txt'
				}
			}
		}


}
}

// org.eclipse.jdt.launching.JRE_CONTAINER/org.eclipse.jdt.internal.debug.ui.launcher.StandardVMType/JavaSE-17
//Users/nimp/.p2/pool/plugins/org.eclipse.justj.openjdk.hotspot.jre.full.macosx.aarch64_17.0.11.v20240426-1830/jre/bin/java
